version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: pinacle
      POSTGRES_USER: pinacle
      POSTGRES_PASSWORD: development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pinacle"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis for session storage and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # Example Next.js Pod
  pod-nextjs-example:
    build:
      context: .
      dockerfile: docker/Dockerfile.nextjs
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - ./workspace/nextjs-example:/workspace
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - postgres
      - redis

  # Example Mastra Pod
  pod-mastra-example:
    build:
      context: .
      dockerfile: docker/Dockerfile.mastra
    ports:
      - "8000:8000"
      - "8081:8080"
    volumes:
      - ./workspace/mastra-example:/workspace
    environment:
      - PYTHON_ENV=development
      - PYTHONPATH=/workspace
    depends_on:
      - postgres
      - redis

  # Example Custom Pod
  pod-custom-example:
    build:
      context: .
      dockerfile: docker/Dockerfile.base
    ports:
      - "8082:8080"
      - "8888:8888"
    volumes:
      - ./workspace/custom-example:/workspace
    environment:
      - DEBIAN_FRONTEND=noninteractive
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:

