import { Code2, Cpu, Terminal, Zap } from "lucide-react";
import type { Bundle } from "../types/setup";

export const bundles: Bundle[] = [
  {
    id: "vite-starter",
    name: "Vite Starter",
    description:
      "A lightweight environment for frontend development with Vite.",
    icon: Zap,
    tier: "dev.small",
    cpuCores: 1,
    memoryGb: 1,
    storageGb: 10,
    pricePerMonth: 6,
    template: "vite",
    services: ["Claude Code", "Vibe Kanban", "Code Server", "Terminal"],
    requiredEnvVars: ["ANTHROPIC_API_KEY"],
    popular: true,
  },
  {
    id: "nextjs-pro",
    name: "Next.js Pro",
    description: "Full-stack Next.js environment with database support.",
    icon: Code2,
    tier: "dev.medium",
    cpuCores: 1,
    memoryGb: 2,
    storageGb: 20,
    pricePerMonth: 12,
    template: "nextjs",
    services: [
      "Claude Code",
      "Vibe Kanban",
      "Code Server",
      "Terminal",
      "Database",
    ],
    requiredEnvVars: ["ANTHROPIC_API_KEY", "NEXTAUTH_SECRET", "DATABASE_URL"],
  },
  {
    id: "custom-setup",
    name: "Custom Setup",
    description: "A blank Ubuntu environment for full customization.",
    icon: Terminal,
    tier: "dev.small",
    cpuCores: 1,
    memoryGb: 1,
    storageGb: 10,
    pricePerMonth: 6,
    template: "ubuntu",
    services: ["Claude Code", "Vibe Kanban", "Code Server", "Terminal"],
    requiredEnvVars: ["ANTHROPIC_API_KEY"],
  },
  {
    id: "power-user",
    name: "Power User",
    description: "High-performance environment for demanding applications.",
    icon: Cpu,
    tier: "dev.large",
    cpuCores: 2,
    memoryGb: 4,
    storageGb: 50,
    pricePerMonth: 24,
    template: "custom",
    services: [
      "Claude Code",
      "Vibe Kanban",
      "Code Server",
      "Terminal",
      "Docker",
    ],
    requiredEnvVars: ["ANTHROPIC_API_KEY"],
  },
];
